### ISSUE TITLE
Clean up HTML Video Element for memory management

### ISSUE THREAD

**Issue by logg926** [evictor/get-blob-duration#11]
Thanks for this awesome and handy library! 
Would like to know in terms of memory management, will the HTML video element created during the runtime get destroy when it is done? 

if not, any timeline for adding it?

**Comment by davidurco** [comment]
@logg926 Video HTML element is not being appended to the DOM, so there's no need to delete it. Read more [here](https://stackoverflow.com/questions/1847220/javascript-document-createelement-delete-domelement).

**Comment by evictor** [comment]
Thx @Hectix
